/**
 * exportSVG: laser-ready SVG in mm.
 *  - width/height in mm, viewBox 0 0 W H (user unit = 1 mm)
 *  - closed compound paths only (M … Z), evenodd, no transforms, no strokes-as-geometry
 *  - duplicate subpaths removed, collinear points removed, 3 decimals
 *  - optional metadata with the project JSON
 */
import { APP_VERSION, type Project } from "../model/project";
import { clean, flattenRegions } from "../geometry/boolean";
import { sheetContour } from "../geometry/stencil/sheet";
import type { Contour, RegionNode, Vec2 } from "../geometry/types";
import { area, simplifyContour } from "../geometry/vec";

export interface SvgExportOptions {
  /** Include the project JSON as <metadata>. */
  metadata?: boolean;
  /** Stroke colour of cut paths. */
  stroke?: string;
  strokeWidth?: number;
  /** Decimal places. */
  precision?: number;
  /** Fill the apertures instead of stroking them (for previews / cutting machines that use fills). */
  fill?: boolean;
}

const DEFAULTS: Required<SvgExportOptions> = { metadata: true, stroke: "#ff0000", strokeWidth: 0.1, precision: 3, fill: false };

export function formatNumber(n: number, precision: number): string {
  const s = n.toFixed(precision);
  const t = s.includes(".") ? s.replace(/0+$/, "").replace(/\.$/, "") : s;
  return t === "-0" ? "0" : t;
}

/** Optimise a contour for export: clean tiny segments, drop collinear points, drop degenerate results. */
export function optimizeContour(c: Contour): Contour | null {
  if (c.length < 3) return null;
  const cleaned = simplifyContour(clean(c, 0.0005), 0.0015);
  if (cleaned.length < 3 || area(cleaned) < 1e-4) return null;
  return cleaned;
}

/** Path data for one closed contour, translated by `offset`. */
export function contourPath(c: Contour, offset: Vec2, precision: number): string {
  let d = "";
  for (let i = 0; i < c.length; i++) {
    const p = c[i]!;
    d += `${i === 0 ? "M" : "L"}${formatNumber(p.x + offset.x, precision)} ${formatNumber(p.y + offset.y, precision)}`;
  }
  return d + "Z";
}

function contourSignature(c: Contour, precision: number): string {
  // Order-independent signature: sorted rounded points. Good enough to detect identical subpaths.
  return c
    .map((p) => `${formatNumber(p.x, precision)},${formatNumber(p.y, precision)}`)
    .sort()
    .join(";");
}

/** Build a compound path (all outers and holes) from a region tree, deduplicated. */
export function regionsPathData(regions: readonly RegionNode[], offset: Vec2, precision: number): { d: string; subpaths: number; dropped: number } {
  const seen = new Set<string>();
  const parts: string[] = [];
  let dropped = 0;
  for (const r of flattenRegions(regions)) {
    for (const raw of [r.outer, ...r.holes]) {
      const c = optimizeContour(raw);
      if (!c) {
        dropped++;
        continue;
      }
      const sig = contourSignature(c, precision);
      if (seen.has(sig)) {
        dropped++;
        continue;
      }
      seen.add(sig);
      parts.push(contourPath(c, offset, precision));
    }
  }
  return { d: parts.join(""), subpaths: parts.length, dropped };
}

const xml = (s: string): string => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export interface SvgExportResult {
  svg: string;
  subpaths: number;
  dropped: number;
}

export function exportSVG(project: Project, finalApertures: readonly RegionNode[], options: SvgExportOptions = {}): SvgExportResult {
  const o = { ...DEFAULTS, ...options };
  const W = project.sheet.width;
  const H = project.sheet.height;
  const offset = { x: W / 2, y: H / 2 };
  const { d, subpaths, dropped } = regionsPathData(finalApertures, offset, o.precision);
  const paint = o.fill ? `fill="#000000" fill-rule="evenodd" stroke="none"` : `fill="none" fill-rule="evenodd" stroke="${o.stroke}" stroke-width="${o.strokeWidth}" stroke-linejoin="round"`;
  const lines: string[] = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${formatNumber(W, o.precision)}mm" height="${formatNumber(H, o.precision)}mm" viewBox="0 0 ${formatNumber(W, o.precision)} ${formatNumber(H, o.precision)}">`,
  );
  lines.push(`<title>${xml(project.name)} — MandalaFab stencil</title>`);
  lines.push(`<desc>Units: mm. Closed cut paths (evenodd). Generated by MandalaFab ${APP_VERSION}.</desc>`);
  if (o.metadata) {
    const json = JSON.stringify({ app: "MandalaFab", version: APP_VERSION, project }).replace(/\]\]>/g, "]]]]><![CDATA[>");
    lines.push(`<metadata><mandalafab:project xmlns:mandalafab="https://fooping-tech.github.io/MandalaFab/ns"><![CDATA[${json}]]></mandalafab:project></metadata>`);
  }
  if (project.sheet.outline) {
    const outline = contourPath(sheetContour(project.sheet), offset, o.precision);
    lines.push(`<path id="outline" d="${outline}" fill="none" stroke="${o.stroke}" stroke-width="${o.strokeWidth}"/>`);
  }
  if (d.length > 0) lines.push(`<path id="apertures" d="${d}" ${paint}/>`);
  lines.push(`</svg>`);
  return { svg: lines.join("\n"), subpaths, dropped };
}

/** Extract an embedded project from an SVG exported by MandalaFab (or null). */
export function projectFromSVG(svgText: string): unknown | null {
  const m = svgText.match(/<mandalafab:project[^>]*><!\[CDATA\[([\s\S]*?)\]\]><\/mandalafab:project>/);
  if (!m) return null;
  try {
    const parsed = JSON.parse(m[1]!.replace(/\]\]\]\]><!\[CDATA\[>/g, "]]>")) as { project?: unknown };
    return parsed.project ?? null;
  } catch {
    return null;
  }
}
